# Generated by Django 4.1.7 on 2023-04-29 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina_nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_nome', models.CharField(max_length=200)),
                ('evento_conteudo', models.TextField()),
                ('data_do_evento', models.DateTimeField()),
                ('imagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noticia_nome', models.CharField(max_length=200)),
                ('noticia_conteudo', models.TextField()),
                ('noticia_data_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('noticia_autor', models.CharField(max_length=200)),
                ('noticia_privacidade', models.BooleanField()),
                ('imagem', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_nome', models.CharField(max_length=200)),
                ('post_conteudo', models.TextField()),
                ('post_autor', models.CharField(max_length=200)),
                ('post_data_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagem', models.TextField()),
                ('ficheiro', models.TextField()),
                ('referencia_youtube', models.TextField()),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemestrado.disciplina')),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta_autor', models.CharField(max_length=200)),
                ('resposta_conteudo', models.TextField()),
                ('resposta_data_pub', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sitemestrado.post')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(related_name='disciplinas', to='sitemestrado.professor'),
        ),
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
