# Generated by Django 4.1.7 on 2023-05-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='ficheiro',
            field=models.TextField(default='Null'),
            preserve_default=False,
        ),
    ]
