# Generated by Django 4.1.7 on 2023-05-09 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0002_aluno_is_public_noticia_ficheiro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='imagem',
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(default=None, related_name='disciplinas', to='sitemestrado.professor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_privacidade',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='disciplina',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sitemestrado.disciplina'),
        ),
        migrations.CreateModel(
            name='Imagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.TextField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.evento')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.noticia')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.post')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.resposta')),
            ],
        ),
        migrations.CreateModel(
            name='Ficheiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ficheiro', models.TextField()),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.evento')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.noticia')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.post')),
                ('resposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.resposta')),
            ],
        ),
    ]
