# Generated by Django 4.1.7 on 2023-05-09 15:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0003_remove_evento_imagem_alter_disciplina_professores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='ficheiro',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ficheiro',
        ),
        migrations.RemoveField(
            model_name='post',
            name='imagem',
        ),
        migrations.AddField(
            model_name='professor',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.evento'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='noticia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.noticia'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.post'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='resposta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.resposta'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='evento',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.evento'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='noticia',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.noticia'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.post'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='resposta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.resposta'),
        ),
    ]
