# Generated by Django 4.1.7 on 2023-05-09 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0004_remove_noticia_ficheiro_remove_noticia_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='noticia_privacidade',
            field=models.BooleanField(default=False),
        ),
    ]
