# Generated by Django 4.1.7 on 2023-05-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0005_alter_noticia_noticia_privacidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='noticia_autor_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_autor_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resposta',
            name='resposta_autor_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
