# Generated by Django 4.1.7 on 2023-05-10 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0006_noticia_noticia_autor_id_post_post_autor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficheiro',
            name='evento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.evento'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='noticia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.noticia'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.post'),
        ),
        migrations.AlterField(
            model_name='ficheiro',
            name='resposta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ficheiros', to='sitemestrado.resposta'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='evento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.evento'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='noticia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.noticia'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='post',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.post'),
        ),
        migrations.AlterField(
            model_name='imagem',
            name='resposta',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='sitemestrado.resposta'),
        ),
    ]
