# Generated by Django 4.1.7 on 2023-05-10 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0008_evento_evento_capa_evento_participantes_alunos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='data_do_evento',
            new_name='evento_data',
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_autor',
            field=models.CharField(default='Duarte Laureano', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='evento_autor_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
