# Generated by Django 4.1.7 on 2023-05-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0009_rename_data_do_evento_evento_evento_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='area_trab',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aluno',
            name='linkedin',
            field=models.TextField(default='zz'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='area_trab',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professor',
            name='linkedin',
            field=models.TextField(default='zz'),
            preserve_default=False,
        ),
    ]
