# Generated by Django 4.1.7 on 2023-05-11 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0010_aluno_area_trab_aluno_linkedin_professor_area_trab_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='is_public',
        ),
        migrations.AddField(
            model_name='aluno',
            name='is_privado',
            field=models.BooleanField(default=False),
        ),
    ]
