# Generated by Django 4.1.7 on 2023-05-11 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0011_remove_aluno_is_public_remove_professor_is_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='evento_local',
            field=models.CharField(default='Online', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='post_capa',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
