# Generated by Django 4.1.7 on 2023-05-12 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0014_alter_noticia_noticia_data_pub_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_nr_respostas',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 41, 40, 29335)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 41, 40, 30337)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 18, 41, 40, 30337)),
        ),
    ]
