# Generated by Django 4.1.7 on 2023-05-12 22:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0017_alter_aluno_imagem_alter_noticia_noticia_data_pub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='imagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 23, 54, 46, 104622)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 23, 54, 46, 105635)),
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 12, 23, 54, 46, 105635)),
        ),
    ]
