# Generated by Django 4.1.7 on 2023-05-13 02:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0018_alter_aluno_imagem_alter_noticia_noticia_data_pub_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ficheiro',
            name='resposta',
        ),
        migrations.RemoveField(
            model_name='imagem',
            name='resposta',
        ),
        migrations.AddField(
            model_name='ficheiro',
            name='ficheiro_nome',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 34, 33, 237377)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 34, 33, 238381)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 34, 33, 238381)),
        ),
    ]
