# Generated by Django 4.1.7 on 2023-05-13 02:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0019_remove_ficheiro_resposta_remove_imagem_resposta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='participantes_alunos',
            field=models.ManyToManyField(default=None, related_name='eventos', to='sitemestrado.aluno'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='participantes_professores',
            field=models.ManyToManyField(default=None, related_name='eventos', to='sitemestrado.professor'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 51, 32, 637419)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 51, 32, 637419)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 3, 51, 32, 638424)),
        ),
    ]
