# Generated by Django 4.1.7 on 2023-05-13 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitemestrado', '0020_alter_evento_participantes_alunos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='participantes_professores',
        ),
        migrations.AddField(
            model_name='aluno',
            name='is_professor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='professores',
            field=models.ManyToManyField(default=None, related_name='disciplinas', to='sitemestrado.aluno'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='noticia_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 15, 40, 15, 212310)),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 15, 40, 15, 213328)),
        ),
        migrations.AlterField(
            model_name='resposta',
            name='resposta_data_pub',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 13, 15, 40, 15, 214345)),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
